name: Ejecutar Bot Pega 3

on:
  schedule:
    - cron: "30 0 * * 1-6"  # Se ejecuta a las 00:30 UTC de lunes a sábado
  workflow_dispatch:         # Permite ejecución manual desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4 pandas scikit-learn deap python-telegram-bot

      - name: Ejecutar Bot Pega 3
        run: |
          python pega3.py
